[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"
#![feature(slice_pattern)]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.7"
fxhash = "0.2.1"
memmap2 = "0.9.3"
num_cpus = "1.16.0"
rayon = "1.8.0"
